import {
  getAgentAdapter,
  labelsInRule,
  renderFixowlWorkflow,
  resolveRepoSettings,
  RUNTIME_TOKEN_SECRET,
  STARTER_ISSUE_TEMPLATE,
  STARTER_ISSUE_TEMPLATE_PATH,
  STARTER_REPO_CONFIG,
  REPO_CONFIG_PATH,
  WORKFLOW_PATH,
} from "@fixowl/core";
import { ACTION_REPO, targetRepos, type CliContext } from "../context.ts";
import {
  branchExists,
  createBranch,
  ensureLabels,
  fileExists,
  openPullRequest,
  putRepoSecret,
  resolveActionRef,
  splitRepoFullName,
  upsertFile,
} from "../github/repo-provisioning.ts";
import { log } from "../log.ts";

export interface ProvisionOptions {
  pr?: boolean;
  noSchedule?: boolean;
}

export async function provisionCommand(
  ctx: CliContext,
  repoArg: string | undefined,
  options: ProvisionOptions,
): Promise<void> {
  const actionRef = await resolveActionRef(ctx.admin, ACTION_REPO);
  for (const repoFullName of targetRepos(ctx.config, repoArg)) {
    log.info(`\nprovisioning ${repoFullName}`);
    const ref = splitRepoFullName(repoFullName);
    const settings = resolveRepoSettings(ctx.config, repoFullName);
    const adapter = getAgentAdapter(settings.agent, settings.agentEnv);
    const { data: repoData } = await ctx.admin.rest.repos.get({ ...ref });
    const defaultBranch = repoData.default_branch;

    // 1. Labels
    const created = await ensureLabels(ctx.admin, ref, labelsInRule(settings.labels));
    log.ok(created.length > 0 ? `labels created: ${created.join(", ")}` : "labels already present");

    // 2. Secrets: runtime PAT + every agent env var, sealed client-side
    await putRepoSecret(ctx.admin, ref, RUNTIME_TOKEN_SECRET, ctx.config.github.runtime_token);
    for (const name of adapter.env) {
      const value = ctx.secrets[name] ?? process.env[name];
      if (value === undefined || value === "") {
        throw new Error(
          `agent env var ${name} is not in secrets.env; cannot provision ${repoFullName}`,
        );
      }
      await putRepoSecret(ctx.admin, ref, name, value);
    }
    log.ok(`secrets sealed and pushed: ${[RUNTIME_TOKEN_SECRET, ...adapter.env].join(", ")}`);

    // 3. Workflow file
    const workflow = renderFixowlWorkflow({
      schedule: options.noSchedule ? null : settings.schedule,
      labels: settings.labels,
      agent: adapter.name,
      agentEnv: adapter.env,
      maxIssuesPerRun: settings.maxIssuesPerRun,
      issueTimeoutMinutes: settings.issueTimeoutMinutes,
      actionRef: actionRef.ref,
      actionRefComment: actionRef.comment,
    });
    if (options.pr === true) {
      const branch = "fixowl/provision-workflow";
      if (!(await branchExists(ctx.admin, ref, branch))) {
        await createBranch(ctx.admin, ref, branch, defaultBranch);
      }
      const result = await upsertFile(ctx.admin, ref, {
        path: WORKFLOW_PATH,
        content: workflow,
        message: "chore: fixowl workflow",
        branch,
      });
      if (result.action === "unchanged") {
        log.ok("workflow already up to date on the provision branch");
      } else {
        const url = await openPrIfMissing(ctx, ref, {
          head: branch,
          base: defaultBranch,
          title: "chore: fixowl workflow",
          body: "Adds or updates the fixowl workflow. Generated by `fixowl provision --pr`.",
        });
        log.ok(`workflow ${result.action} via PR: ${url}`);
      }
    } else {
      const result = await upsertFile(ctx.admin, ref, {
        path: WORKFLOW_PATH,
        content: workflow,
        message: "chore: fixowl workflow",
        branch: defaultBranch,
      });
      log.ok(`workflow ${result.action}${options.noSchedule ? " (workflow_dispatch only)" : ""}`);
    }

    // 4. Starter repo files, proposed via PR so maintainers stay in the loop
    const missing: Array<{ path: string; content: string }> = [];
    if (!(await fileExists(ctx.admin, ref, REPO_CONFIG_PATH))) {
      missing.push({ path: REPO_CONFIG_PATH, content: STARTER_REPO_CONFIG });
    }
    if (!(await fileExists(ctx.admin, ref, STARTER_ISSUE_TEMPLATE_PATH))) {
      missing.push({ path: STARTER_ISSUE_TEMPLATE_PATH, content: STARTER_ISSUE_TEMPLATE });
    }
    if (missing.length === 0) {
      log.ok("starter files already present (.fixowl.yml, issue template)");
    } else {
      const branch = "fixowl/provision-files";
      if (await branchExists(ctx.admin, ref, branch)) {
        log.warn(`branch ${branch} already exists; review or delete its PR first`);
      } else {
        await createBranch(ctx.admin, ref, branch, defaultBranch);
        for (const file of missing) {
          await upsertFile(ctx.admin, ref, {
            path: file.path,
            content: file.content,
            message: `chore: add ${file.path} for fixowl`,
            branch,
          });
        }
        const url = await openPrIfMissing(ctx, ref, {
          head: branch,
          base: defaultBranch,
          title: "chore: fixowl starter files",
          body:
            "Starter `.fixowl.yml` and issue template for fixowl. " +
            "Edit the verify commands for this repo before merging.",
        });
        log.ok(`starter files proposed: ${url} (${missing.map((f) => f.path).join(", ")})`);
      }
    }

    if (repoData.private === false && options.noSchedule !== true) {
      log.warn(
        "public repo: GitHub pauses scheduled workflows after 60 days without repo activity; `fixowl status` reminds you",
      );
    }
  }
}

async function openPrIfMissing(
  ctx: CliContext,
  ref: { owner: string; repo: string },
  params: { head: string; base: string; title: string; body: string },
): Promise<string> {
  const { data: existing } = await ctx.admin.rest.pulls.list({
    ...ref,
    state: "open",
    head: `${ref.owner}:${params.head}`,
  });
  const first = existing[0];
  if (first !== undefined) return first.html_url;
  return await openPullRequest(ctx.admin, ref, params);
}
