import type { LabelRule } from "./labels.ts";

/**
 * Renders the workflow file fixowl provisions into each target repo.
 *
 * The workflow is deliberately dumb: all logic lives in the fixowl action.
 * There is no `container:` key anywhere; containerization is expressed only as
 * the action's own explicit `docker run`, which is what keeps this file
 * portable: swapping `runs-on` to `ubuntu-latest` is the one-line cloud move.
 */

export const WORKFLOW_PATH = ".github/workflows/fixowl.yml";

/** Name of the repo Actions secret holding the runtime PAT (never GITHUB_TOKEN: PRs made with GITHUB_TOKEN do not trigger the target repo's own CI). */
export const RUNTIME_TOKEN_SECRET = "FIXOWL_GITHUB_TOKEN";

const CHECKOUT_PIN = "actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6";
const UPLOAD_ARTIFACT_PIN = "actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5";

export interface WorkflowTemplateOptions {
  /** Cron expression, or null for workflow_dispatch only (provision --no-schedule). */
  schedule: string | null;
  labels: LabelRule;
  agent: string;
  /** Env var names the agent adapter needs; each is wired from a same-named repo secret. */
  agentEnv: readonly string[];
  maxIssuesPerRun: number;
  issueTimeoutMinutes: number;
  /** Default model for issues carrying no selector label; omitted when unset. */
  defaultModel?: string;
  /** Default reasoning effort for issues carrying no selector label; omitted when unset. */
  defaultEffort?: string;
  /** Selector-label -> {model, effort} map; omitted when empty. */
  labelModels?: Record<string, { model: string; effort: string }>;
  /** e.g. "NachoPal/fixowl@<sha>" */
  actionRef: string;
  /** Trailing comment after the action ref, e.g. "v0 (main @ 2026-09-02)". */
  actionRefComment?: string;
  /** Defaults to the self-hosted fixowl runner; set "ubuntu-latest" for cloud. */
  runsOn?: string;
}

export function renderFixowlWorkflow(options: WorkflowTemplateOptions): string {
  const runsOn = options.runsOn ?? "[self-hosted, fixowl]";
  // The `source` input lets the local fallback trigger tag its dispatch
  // (source: scheduled-fallback), which the run-name surfaces as a marker and
  // the action's once-a-day budget guard reads. Manual runs leave it blank.
  const dispatchBlock = `  workflow_dispatch:
    inputs:
      source:
        description: "Internal: the local fallback trigger sets this to scheduled-fallback; leave blank for manual runs."
        required: false
        default: ""`;
  const onBlock = options.schedule
    ? `on:
  schedule:
    - cron: "${options.schedule}"
${dispatchBlock}`
    : `on:
${dispatchBlock}`;

  const secretEnv = [RUNTIME_TOKEN_SECRET, ...options.agentEnv]
    .map((name) => `          ${name}: \${{ secrets.${name} }}`)
    .join("\n");

  const refComment = options.actionRefComment ? ` # ${options.actionRefComment}` : "";

  // Model/effort inputs are only rendered when set, so today's workflows (no
  // model selection) are byte-for-byte unchanged. label-models is a JSON string.
  const withLines = [
    `          labels-any: "${(options.labels.any ?? []).join(",")}"`,
    `          labels-all: "${(options.labels.all ?? []).join(",")}"`,
    `          agent: ${options.agent}`,
    `          agent-env: "${options.agentEnv.join(",")}"`,
    `          max-issues-per-run: "${options.maxIssuesPerRun}"`,
    `          issue-timeout-minutes: "${options.issueTimeoutMinutes}"`,
    `          source: "\${{ github.event.inputs.source }}"`,
  ];
  // The cron is passed to the action so its once-a-day budget guard can anchor
  // the "already ran" window to the schedule occurrence (correct across UTC
  // midnight) rather than the UTC calendar day. Omitted for a dispatch-only
  // workflow, where the guard degrades to the calendar day harmlessly.
  if (options.schedule) {
    withLines.push(`          schedule: "${options.schedule}"`);
  }
  if (options.defaultModel !== undefined) {
    withLines.push(`          default-model: "${options.defaultModel}"`);
  }
  if (options.defaultEffort !== undefined) {
    withLines.push(`          default-effort: "${options.defaultEffort}"`);
  }
  if (options.labelModels !== undefined && Object.keys(options.labelModels).length > 0) {
    // Double JSON.stringify: the inner JSON becomes a YAML double-quoted scalar.
    withLines.push(
      `          label-models: ${JSON.stringify(JSON.stringify(options.labelModels))}`,
    );
  }

  return `# Generated by fixowl. Re-run \`fixowl provision\` to update; manual edits will be overwritten.
name: fixowl
run-name: "fixowl night run\${{ github.event.inputs.source == 'scheduled-fallback' && ' [scheduled-fallback]' || '' }}"

${onBlock}

permissions:
  contents: read
  actions: read # the once-a-day budget guard lists this workflow's runs

concurrency:
  group: fixowl
  cancel-in-progress: false

jobs:
  fixowl:
    runs-on: ${runsOn}
    timeout-minutes: 300
    steps:
      # Security guard: if a previous run was hard-killed mid-night, the
      # workspace .git may be one an agent container planted. Checkout must
      # never run git against it, so every night starts from a clean clone.
      - name: Reset workspace git state
        run: rm -rf "$GITHUB_WORKSPACE/.git" "$GITHUB_WORKSPACE.fixowl-git"

      - uses: ${CHECKOUT_PIN}
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ${options.actionRef}${refComment}
        with:
${withLines.join("\n")}
        env:
          GITHUB_TOKEN: \${{ github.token }} # Actions: read, for the once-a-day budget guard
${secretEnv}

      - uses: ${UPLOAD_ARTIFACT_PIN}
        if: always()
        with:
          name: fixowl-evidence
          path: \${{ runner.temp }}/fixowl-evidence/
          if-no-files-found: ignore
`;
}
