import type { LabelRule } from "./labels.ts";

/**
 * Renders the workflow file fixowl provisions into each target repo.
 *
 * The workflow is deliberately dumb: all logic lives in the fixowl action.
 * There is no `container:` key anywhere; containerization is expressed only as
 * the action's own explicit `docker run`, which is what keeps this file
 * portable: swapping `runs-on` to `ubuntu-latest` is the one-line cloud move.
 */

export const WORKFLOW_PATH = ".github/workflows/fixowl.yml";

/** Name of the repo Actions secret holding the runtime PAT (never GITHUB_TOKEN: PRs made with GITHUB_TOKEN do not trigger the target repo's own CI). */
export const RUNTIME_TOKEN_SECRET = "FIXOWL_GITHUB_TOKEN";

const CHECKOUT_PIN = "actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6";
const UPLOAD_ARTIFACT_PIN = "actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5";

export interface WorkflowTemplateOptions {
  /** Cron expression, or null for workflow_dispatch only (provision --no-schedule). */
  schedule: string | null;
  labels: LabelRule;
  agent: string;
  /** Env var names the agent adapter needs; each is wired from a same-named repo secret. */
  agentEnv: readonly string[];
  maxIssuesPerRun: number;
  issueTimeoutMinutes: number;
  /** e.g. "NachoPal/fixowl@<sha>" */
  actionRef: string;
  /** Trailing comment after the action ref, e.g. "v0 (main @ 2026-09-02)". */
  actionRefComment?: string;
  /** Defaults to the self-hosted fixowl runner; set "ubuntu-latest" for cloud. */
  runsOn?: string;
}

export function renderFixowlWorkflow(options: WorkflowTemplateOptions): string {
  const runsOn = options.runsOn ?? "[self-hosted, fixowl]";
  const onBlock = options.schedule
    ? `on:
  schedule:
    - cron: "${options.schedule}"
  workflow_dispatch: {}`
    : `on:
  workflow_dispatch: {}`;

  const secretEnv = [RUNTIME_TOKEN_SECRET, ...options.agentEnv]
    .map((name) => `          ${name}: \${{ secrets.${name} }}`)
    .join("\n");

  const refComment = options.actionRefComment ? ` # ${options.actionRefComment}` : "";

  return `# Generated by fixowl. Re-run \`fixowl provision\` to update; manual edits will be overwritten.
name: fixowl
run-name: "fixowl night run"

${onBlock}

permissions:
  contents: read

concurrency:
  group: fixowl
  cancel-in-progress: false

jobs:
  fixowl:
    runs-on: ${runsOn}
    timeout-minutes: 300
    steps:
      - uses: ${CHECKOUT_PIN}
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ${options.actionRef}${refComment}
        with:
          labels-any: "${(options.labels.any ?? []).join(",")}"
          labels-all: "${(options.labels.all ?? []).join(",")}"
          agent: ${options.agent}
          agent-env: "${options.agentEnv.join(",")}"
          max-issues-per-run: "${options.maxIssuesPerRun}"
          issue-timeout-minutes: "${options.issueTimeoutMinutes}"
        env:
${secretEnv}

      - uses: ${UPLOAD_ARTIFACT_PIN}
        if: always()
        with:
          name: fixowl-evidence
          path: \${{ runner.temp }}/fixowl-evidence/
          if-no-files-found: ignore
`;
}
